name: Publish Model Metrics

on:
  push:
    branches: [ main ]

jobs:
  publish-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - uses: iterative/setup-cml@v2
      
      
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Generate Report
        run: |
          echo "## CI Run Report" >> report.md
          echo "Model Accuracy: $(jq -r '.accuracy.precision' results/metrics.json)" >> report.md
          echo "Weighted F1-Score: $(jq -r '."weighted avg"."f1-score"' results/metrics.json)" >> report.md
          echo "*New model artifact created and tested.*" >> report.md
      - name: Publish Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md
